name: Fetch Jobs

on:
  schedule:
    - cron: "10,40 * * * 1-5" # every half hour on weekdays
    - cron: "0 */2 * * 6,0" # every two hours on weekends
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: jobs-json-update
  cancel-in-progress: false

jobs:
  fetch_jobs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: jobs/package-lock.json

      - name: Install dependencies
        working-directory: jobs
        run: |
          npm ci

      - name: Fetch jobs
        working-directory: jobs
        run: npm run fetch

      - name: Git Pull Latest Changes
        run: git pull origin ${{ github.ref_name }}

      - name: Classify jobs
        working-directory: jobs
        run: npm run classify

      - name: Analyze jobs data
        working-directory: jobs
        run: npm run analyze

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "build: updated Jobs data"
          # Target all .json files inside /jobs
          file_pattern: "jobs/*.json*"
