name: Sanity Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: config/package-lock.json

      - name: Install dependencies
        working-directory: config
        run: npm ci

      # Make locally installed CLIs discoverable without npx
      - name: Add node_modules to PATH
        run: echo "${GITHUB_WORKSPACE}/config/node_modules/.bin" >> $GITHUB_PATH

      - name: Generate PWA files
        if: github.event_name == 'push'
        env:
          NODE_PATH: "${{ github.workspace }}/config/node_modules"
        run: node ./build-pwa.js

      - name: Validate HTML
        run: htmlhint --config config/.htmlhintrc .

      - name: Validate CSS
        run: |
          css_files=$(find . -name "*.css" -type f -size +0c)
          csslint --errors=box-model,duplicate-properties,empty-rules,universal-selector $css_files

      - name: Validate JS
        run: eslint -c config/.eslintrc.js "**/*.js" --ignore-pattern config/.eslintrc.js

      - name: Validate Spelling
        uses: rojopolis/spellcheck-github-actions@0.54.0
        with:
          config_path: config/.spellcheck.yml
          task_name: HTML

      # Restore the specific cache for this branch
      - name: Restore lychee cache
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.ref_name }}
          restore-keys: cache-lychee-main

      # Run Lychee and output updates to local file
      - name: Validate Broken Links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --cache --max-cache-age 1d --root-dir ${{ github.workspace }} --verbose --no-progress --output .lycheecache "./**/*.md" "./**/*.html" --exclude-path "node_modules"

      # Save the new cache
      - name: Save lychee cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.ref_name }}

      - name: Commit and push if changed
        if: github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "build: Auto-generate PWA files"
          file_pattern: "index.html service-worker.js"
